[package]
name = "reqwest"
version = "0.1.0"
authors = ["Luca Casonato <hello@lcas.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.1", features = ["full"] }
reqwest = { version = "0.11.3", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
futures = "0.3.15"

[features]
pool = []